/*
SQLyog Ultimate v12.08 (64 bit)
MySQL - 8.0.27 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `sys_menu` (
	`id` bigint (20),
	`pid` bigint (20),
	`sub_count` int (10),
	`type` int (10),
	`title` varchar (765),
	`name` varchar (765),
	`component` varchar (765),
	`menu_sort` int (10),
	`icon` varchar (765),
	`path` varchar (765),
	`i_frame` bit (1),
	`cache` bit (1),
	`hidden` bit (1),
	`permission` varchar (765),
	`create_by` bigint (20),
	`update_by` bigint (20),
	`create_time` datetime ,
	`update_time` datetime ,
	`is_deleted` bit (1)
); 
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('1','0','7','0','系统管理','','','1','system','system','','','','','1','1','2018-12-18 15:11:29','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('2','1','3','1','用户管理','User','system/user/index','2','peoples','user','','','','user:list','1','1','2018-12-18 15:14:44','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('3','1','3','1','角色管理','Role','system/role/index','3','role','role','','','','roles:list','1','1','2018-12-18 15:16:07','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('5','1','3','1','菜单管理','Menu','system/menu/index','5','menu','menu','','','','menu:list','1','1','2018-12-18 15:17:28','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('6','0','4','0','系统监控','','','10','monitor','monitor','','','','','1','1','2018-12-18 15:17:48','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('7','6','0','1','操作日志','Log','monitor/log/index','11','log','logs','','','','','1','1','2018-12-18 15:18:26','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('28','1','3','1','任务调度','Timing','system/timing/index','999','timing','timing','','','','timing:list','1','1','2019-01-07 20:34:40','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('32','6','0','1','异常日志','ErrorLog','monitor/log/errorLog','12','error','errorLog','','','','','1','1','2019-01-13 13:49:03','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('35','1','3','1','部门管理','Dept','system/dept/index','6','dept','dept','','','','dept:list','1','1','2019-03-25 09:46:00','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('37','1','3','1','岗位管理','Job','system/job/index','7','Steve-Jobs','job','','','','job:list','1','1','2019-03-29 13:51:18','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('39','1','3','1','字典管理','Dict','system/dict/index','8','dictionary','dict','','','','dict:list','1','1','2019-04-10 11:49:04','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('41','6','0','1','在线用户','OnlineUser','monitor/online/index','10','Steve-Jobs','online','','','','','1','1','2019-10-26 22:08:43','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('44','2','0','2','用户新增','','','2','','','','','','user:add','1','1','2019-10-29 10:59:46','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('45','2','0','2','用户编辑','','','3','','','','','','user:edit','1','1','2019-10-29 11:00:08','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('46','2','0','2','用户删除','','','4','','','','','','user:del','1','1','2019-10-29 11:00:23','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('48','3','0','2','角色创建','','','2','','','','','','roles:add','1','1','2019-10-29 12:45:34','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('49','3','0','2','角色修改','','','3','','','','','','roles:edit','1','1','2019-10-29 12:46:16','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('50','3','0','2','角色删除','','','4','','','','','','roles:del','1','1','2019-10-29 12:46:51','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('52','5','0','2','菜单新增','','','2','','','','','','menu:add','1','1','2019-10-29 12:55:07','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('53','5','0','2','菜单编辑','','','3','','','','','','menu:edit','1','1','2019-10-29 12:55:40','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('54','5','0','2','菜单删除','','','4','','','','','','menu:del','1','1','2019-10-29 12:56:00','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('56','35','0','2','部门新增','','','2','','','','','','dept:add','1','1','2019-10-29 12:57:09','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('57','35','0','2','部门编辑','','','3','','','','','','dept:edit','1','1','2019-10-29 12:57:27','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('58','35','0','2','部门删除','','','4','','','','','','dept:del','1','1','2019-10-29 12:57:41','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('60','37','0','2','岗位新增','','','2','','','','','','job:add','1','1','2019-10-29 12:58:27','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('61','37','0','2','岗位编辑','','','3','','','','','','job:edit','1','1','2019-10-29 12:58:45','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('62','37','0','2','岗位删除','','','4','','','','','','job:del','1','1','2019-10-29 12:59:04','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('64','39','0','2','字典新增','','','2','','','','','','dict:add','1','1','2019-10-29 13:00:17','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('65','39','0','2','字典编辑','','','3','','','','','','dict:edit','1','1','2019-10-29 13:00:42','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('66','39','0','2','字典删除','','','4','','','','','','dict:del','1','1','2019-10-29 13:00:59','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('73','28','0','2','任务新增','','','2','','','','','','timing:add','1','1','2019-10-29 13:07:28','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('74','28','0','2','任务编辑','','','3','','','','','','timing:edit','1','1','2019-10-29 13:07:41','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('75','28','0','2','任务删除','','','4','','','','','','timing:del','1','1','2019-10-29 13:07:54','2020-12-13 16:25:07','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('123','0','4','0','平台管理','','','100','java','tiku1','','','','','1','1','2022-04-14 09:28:34','2022-04-14 09:28:34','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('124','123','0','1','轮播图','Lunbo','tiku/lunbo/index','16','message','lunbo','','','','lunbo:list','1','1','2022-04-14 09:29:26','2022-04-14 09:29:26','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('125','123','0','1','分类管理','Classify','tiku/classify/index','17','money','classify','','','','classify:list','1','1','2022-04-14 09:31:22','2022-04-14 09:31:22','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('126','123','0','1','案例管理','CaseManage','tiku/caseManage/index','18','visits','caseManage','','','','caseManage:list','1','1','2022-04-14 09:32:11','2022-04-14 09:32:11','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('127','0','1','0','机构管理','','','200','system1','tiku2','','','','','1','1','2022-04-14 09:32:48','2022-04-14 09:32:48','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('128','127','0','1','学生管理','Students','tiku/students/index','201','shopping','students','','','','students:list','1','1','2022-04-14 09:33:34','2022-04-14 09:33:34','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('129','0','1','0','题库管理','','','300','theme','tiku3','','','','','1','1','2022-04-14 09:33:57','2022-04-14 09:33:57','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('130','123','0','1','学习资料管理','StudyManage','tiku/studyManage/index','19','validCode','studyManage','','','','studyManage:list','1','1','2022-04-14 09:38:20','2022-04-14 09:38:20','');
insert into `sys_menu` (`id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`, `is_deleted`) values('131','129','0','1','题库','Exercise','tiku/exercise/index','301','alipay','exercise','','','','exercise:list','1','1','2022-04-14 09:38:20','2022-04-14 09:38:20','');
